/**
 * Public Firebase web-app config — safe to commit (implementation.md §11, §15).
 * Generated by scripts/setup-firebase.ts — do not hand-edit; re-run the script instead.
 */
export const firebaseConfig = {
  apiKey: "AIzaSyA2FLEoFbbrAhzLKFCiAI1oBiaQk0ORH0o",
  authDomain: "adventure-3d-inc.firebaseapp.com",
  projectId: "adventure-3d-inc",
  storageBucket: "adventure-3d-inc.firebasestorage.app",
  messagingSenderId: "1034047468064",
  appId: "1:1034047468064:web:d07c06c386a411efb38245",
};
